### ISSUE TITLE
New release v2.0.0 ?

### ISSUE THREAD

**Issue by rousan** [rousan/multer-rs#35]
@SergioBenitez, @jebrosen, is there any pending issues to be solved yet? I think we should make a new release as soon as possible. Please let me know, if the master branch is stable, so I can make a new release.

**Comment by SergioBenitez** [comment]
I'm looking into merging #33 now. Once it's in, feel free to release!

**Comment by rousan** [comment]
Sure, let me know when it's merged. Thanks.

**Comment by SergioBenitez** [comment]
Okay, I think we're ready.

**Comment by rousan** [comment]
@SergioBenitez, thanks for your quick contribution. So, I am preparing for new release from `master` branch as a major release.

**Comment by SergioBenitez** [comment]
This needs a major release due to several breaking changes.

**Comment by rousan** [comment]
Released [`v2.0.0`](https://crates.io/crates/multer)
