### ISSUE TITLE
Add an option to deserialize the full multipart body into a type using serde Deserializer

### ISSUE THREAD

**Issue by rousan** [rousan/multer-rs#6]
Discussion: https://www.reddit.com/r/rust/comments/gh2j9e/multer_async_multipartformdata_parser_for_rust/

**Comment by SergioBenitez** [comment]
I think this should be considered out-of-scope for `multer`. One can write a library _using_ `multer`, external to `multer`, that does (de)serialization.

**Comment by rousan** [comment]
Yes, makes sense.
