### ISSUE TITLE
Please provide a way to share CVE in this library

### ISSUE THREAD

**Issue by IvanGoncharov** [rousan/multer-rs#63]
I identified CVE in this library and am working on a fix, but I don't know how to share it with maintainers of this library.

Please enable security advisories on this repo:
https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/creating-a-repository-security-advisory

cc: @atezet @ELD @hdoordt @rousan @SergioBenitez 
I sent you all an email (ivan at apollographql.com) on Thursday with the CVE description.
Can you please specify a way for me to disclose this CVE in a responsible manner?

**Comment by SergioBenitez** [comment]
Apologies, have been on vacation. Just saw your email - will push a fix ASAP. I've also enabled the security disclosure feature.

**Comment by IvanGoncharov** [comment]
Closing since the discussion is moved into security advisory.
