### ISSUE TITLE
Provide accurate error information.

### ISSUE THREAD

**Issue by sunli829** [rousan/multer-rs#9]
It looks great, I have switched my project to multer (https://github.com/async-graphql/async-graphql). But it would be better if it could provide more accurate error information than just a string.

**Comment by rousan** [comment]
You mean in an enum type like ErrorKind?

**Comment by rousan** [comment]
I will change the struct Error to enum variants and will make a release `v1.0.4` soon.

**Comment by sunli829** [comment]
Thank you.😃

**Comment by rousan** [comment]
Hey @sunli829 , I just released `v1.1.1` with better error debugging: 

Just update `multer` version to
```toml
multer = "1.1.1"
```

https://docs.rs/multer/1.1.1/multer/enum.Error.html

**Comment by sunli829** [comment]
Thank you very much, it looks great now. 😁
